version: "3.9"

services:
  app_task:
    container_name: task_junior
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    environment:
     APP_HOST: "0.0.0.0"
     APP_PORT: "8787"
     READ_TIMEOUT: "3s"
     WRITE_TIMEOUT: "3s"
     IDLE_TIMEOUT: "6s"
     SHUTDOWN_TIMEOUT: "10s"
    depends_on:
      - postgres
  postgres:
    container_name: db_task
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: Account
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "49159:5432"